[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[scheduled.functions]]
  name = "crawl-yelp"
  cron = "0 3 * * *" # daily 03:00 UTC

[[scheduled.functions]]
  name = "crawl-google"
  cron = "0 4 * * *" # daily 04:00 UTC

